Vagrant.configure("2") do |config|
  config.vm.provision "docker" do |d|
    d.run "postgres-camping",
      image: "postgres",
      daemonize: true,
      args: "-p 127.0.0.1:5432:5432 -e POSTGRES_DB=camping -e POSTGRES_PASSWORD=test -e POSTGRES_USER=test"
  end
end
